# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4d67f6a57d8f17591b400d86c53219b44a33f4cf6103c1764ee356d331efce4107d9ab5f46e6f1079facba4a0069bec308dc297067823fe8ebc54da0b05758

test:
  secret_key_base: facb395e048940f855c38e388226a87294cef25285167658e949a6e7ba58ca0678b493b449c49c92a05a5cc33059176a2d3c92004509b6a9cebab77c1ca716e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
